### PR TITLE
Impl device discorvery on Linux

### PR DESCRIPTION
**Pull request by Sunbreak**

### CODE REVIEW

**Comment by Sunbreak** [comment]
cc @rohitsangwan01

**Comment by rohitsangwan01** [comment]
@Sunbreak are you planning to merge other features too ??

**Comment by Sunbreak** [comment]
> @Sunbreak are you planning to merge other features too ??

Not this week. Working on docs for the moment

**Comment by Sunbreak** [comment]
BTW, `quick_blue` 0.4.0 & `quick_blue_linux` 0.1.0 are published

**Comment by rohitsangwan01** [comment]
@Sunbreak  also i think pub points can be improved , currently its 70 /130

**Comment by Sunbreak** [comment]
Yep. Gonna to.

`bluez` 0.7.9 is here compatible with Flutter 2.0.0

**Comment by rohitsangwan01** [comment]
yeah just checked ,great , and also  except MTU  , we can implement all functionalities , including notification subsl , there is a workaround for this within bluez package without any timer or loop ,

**Comment by rohitsangwan01** [comment]
and for web , this library really includes all cases https://pub.dev/packages/flutter_web_bluetooth , and provides everything in Stream , so much easier to integrate

**Comment by Sunbreak** [comment]
> and for web , this library really includes all cases https://pub.dev/packages/flutter_web_bluetooth , and provides everything in Stream , so much easier to integrate

I'll check it. Thanks bro

**Pull request merged**
