### PR TITLE
service callback with characteristic & bluetooth device name except local name windows

### PR DESCRIPTION
**Pull request by Bikram40**

### CODE REVIEW

**Comment by Sunbreak** [comment]
Could you rebase and resolve the conflicts?

You are adding characteristic to `onServiceDiscovered`. Could you elaborate the use case?

**Comment by bikram0000** [comment]
I will rebase and resolve.
if we need to send data to the printer then we need characteristics starting with "49535343-8841"

**Comment by Sunbreak** [comment]
Then I would like to use pairs of service to characteristic like https://github.com/woodemi/quick_blue/blob/34a24e57bacf608e54a161a2ef164535984d9971/quick_blue/android/src/main/kotlin/com/example/quick_blue/QuickBluePlugin.kt#L284

**Comment by Sunbreak** [comment]
Sorry, we have add Linux support and here are conficts again

**Comment by Sunbreak** [comment]
Closing this PR infavor of https://github.com/woodemi/quick_blue/pull/83 and https://github.com/woodemi/quick_blue/pull/94

**Pull request closed without merging**
