### PR TITLE
feature: add readValue & logLevel

### PR DESCRIPTION
**Pull request by Yongle-Fu**

### CODE REVIEW

**Comment by Sunbreak** [comment]
Would you split the PR into two: one of `log` and one of `readValue`?

Actually we need other platforms' implementation of `readValue`.

And it is not a good idea to pass `std::unique_ptr<flutter::MethodResult` as a parameter to `ReadValueAsync` on Windows.

BTW, we could chat on WeChat: `wk2311007`

**Comment by Sunbreak** [comment]
`readValue` is added https://github.com/woodemi/quick_blue/pull/49

I've test the PR on Android/iOS/macOS but not Windows.

I don't have a Windows by my side. Could you help to test it on Windows?

**Comment by Yongle-Fu** [comment]
> 
OK, Thank you, you are right

**Comment by Sunbreak** [comment]
BTW, we could chat on WeChat: `wk2311007`

There is a large group of Flutter Desktop (aka Windows/macOS) developers here

**Comment by Yongle-Fu** [comment]
ok, i can test it on Windows, and added WeChat: wk2311007

**Pull request closed without merging**
